config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  get 'index' => "homes#index"
  get 'about' => "homes#about"

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :comments, only: [:edit, :update]
  resources :favourites, only: [:index]

  resources :users, only: [:new, :create, :show, :edit, :update]

  get "/users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "/users/:id/edit_password" => "users#update_password", as: :update_password

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  get "/search" => "posts#search"
  post "/search" => "posts#search"
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  attr_accessor :tweet_post

  mount_uploaders :images, ImagesUploader

  belongs_to :user
  belongs_to :category

  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  validates :title, presence: true, uniqueness: true, length: { minimum: 7}
  validates :body, presence: true

  before_create :format_case

  scope :recent, -> (number = 5){ order("created_at DESC").limit(number)}
  scope :search_blog, -> (term = ""){ where(["title ILIKE ? OR body ILIKE ?", "%#{term}", "%#{term}%" ]).order("updated_at DESC")}

  def body_snippet
    if self.body.length >= 100
      snippet = "#{self.body[1..100]} ... "
    else
      self.body
    end
  end

  def user_full_name
    user.full_name if user
  end

  def favourite_for(user)
    favourites.find_by(user_id: user)
  end

  def category_title
    category.title if category
  end


    private

      def format_case
          self.title = self.title.titleize
          self.body = self.body.humanize
      end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController <  Api::BaseController

  def index
    @posts = Post.order("created_at ASC").limit(2)
    render json: @posts
  end

  def show
    @post = Post.find(params[:id])
    render json: @post
  end

  def create
    # is found for us in the authenticate method
    # user = User.find_by(api_key: params[:api_key])
    post_params = params.require(:post).permit(:title, :body)
    post = Post.new(post_params)
    post.user = @user
    if post.save
      head :ok
    else
      render json:  { errors: post.errors.full_messages}
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    # @page = params[:page].to_i
    # page = @page * 10
    @posts = Post.order("created_at DESC").page(params[:page]).per(10)
    respond_to do |format|
      format.html { render }
      format.json { render json: @posts.select(:id, :title, :body)}
    end
    # @posts = Post.order("created_at DESC").offset(page).limit(10)
  end
  # .offset("#{current_page * per_page_count}").limit("#{per_page_count}")

  def new
    @post = Post.new
  end

  def create
    # binding.pry
    @post = Post.new(post_params)
    # we don't have access to the @current_user, but we access it through the method
    @post.user = current_user
      if @post.save
        if @post.tweet_post
          client = Twitter::REST::Client.new do |config|
            config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
            config.consumer_secret     = ENV["TWITTER_SECRET_KEY"]
            config.access_token        = current_user.twitter_token
            config.access_token_secret = current_user.twitter_secret
          end
          client.update("new post #{@post.title} @ #{root_url} ")
        end
       redirect_to post_path(@post), flash: {info: "Posted!"}
      else
        flash[:warning] = "post failure"
        render :new
      end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC").page(params[:page]).per(6)
    # @post = Post.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def edit
    # @post = Post.find(params[:id])
  end

  def update
    @post.slug = nil
    # @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), flash: { info: "posted ^_^" }
    else
      flash[:warning] = "Update Not Successful -- Check Errors Below"
      render :edit
    end
  end

  def destroy
    # post = Post.find(params[:id])
    @post.delete
    redirect_to root_path, flash: { warning: "Post deleted" }
  end

  def search
    if params[:search_term]
      @search_results = Post.search_blog(params[:search_term])
    end
  end


      private

      def post_params
        params.require(:post).permit(:title, :category_id, :body, {images: []}, :tweet_post)
      end

      def find_post
        @post = Post.friendly.find(params[:id])
      end

      # def authorize_user
        # if @post.user != current_user
          # redirect_to root_path , alert: "Access Denied"
        # end
      # end

      def authorize_user
        unless can? :manage, @post
        redirect_to root_path , flash: { info: "Access Denied" }
        end
      end


end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<h1 class = "text-lg-center title">New Post</h1>

<% if @post.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-info">
  <ul>
    <% @post.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <%= form_for @post do |f| %>
    <div class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class = "form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select(:category, Category.order(:title), :id, :title, class: "form-control") %>
    </div>
    <div class="form-group">
    <%= f.file_field :images, multiple: true, class: "form-control " %>
    </div>
    <div class="form-group">
      <%= f.check_box :tweet_post %> Tweet Post
    </div>
    <div class = "form-group">
    <%= f.submit "Post Post", class: "btn btn-info-outline btn-block" %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "post" %>

app/views/posts/index.html.erb
<h1 class = "title text-lg-center">Current posts: (<%= @posts.length %>)</h1>

<article class="row">
  <section class="col-md-6 col-md-offset-3">
    <% if @posts %>
    <ul class = "posts">
      <% @posts.each do |post| %>
      <li>
        <p><%= link_to post.title, post_path(post) %></p>
        <p class="text-muted posted-by">(<%= post.user_full_name  %>)</p>
      </li>
      <% end %>
      </ul>
    <% end %>
  </section>
</article>
<section class="row">
  <div class="col-md-6 col-md-offset-3 text-lg-center">
    <%= paginate @posts %>
  </div>
</section>


<%#``  %>
<%# link_to_unless((@page - 1 < 0), "previous", posts_path(page: (@page - 1)) ) do |page| %>
<%# end %>
<%# link_to "next", posts_path(page: (@page + 1) ) %>




<!-- API: public methods made available by the rails gem. is this ruby? is this rails? etc. etc.
form_for: view constructs
return value of tags into stringy html. evaluates and generates html.
both generate form tags: form for is meant to be used with active record objects
form for takes one argument: activerecord object - usually instance variable, do |f|
end

form for to send yourself data with params. maps html to params hash, leverage forms to sanitize inputs///cohesions -->

app/views/posts/new.html.erb
<h1 class = "text-lg-center title">New Post</h1>
<%= render "post" %>

app/views/posts/search.html.erb
<h3>Search the blog...</h3>
<%= form_tag('/search', method: :post) do %>
  <div>
    <%= label_tag :search_term, "Enter search term..." %>
    <%= text_field_tag :search_term %>
  </div>
  <hr>
  <div>
    <%= submit_tag "Search!" %>
  </div>
<% end %>


<% if @search_results %>
<ul>
  <% @search_results.each do |result|  %>
    <li><%= link_to result.title, post_path(result) %></li>
  <% end %>
  </ul>
<% end %>

app/views/posts/show.html.erb
<article class="row">
  <section class="col-md-10 col-md-offset-1">
    <h1 class = "title"><%= @post.title %></h1>
    <p><%= @post.body %></p>
    <p class = "text-muted"><%= @post.category_title %></p>
    <p class = 'text-muted posted-by'>(created by <%= @post.user_full_name %>)</p>
    <%# favourite a post %>
    <% favourite = @post.favourite_for(current_user) %>
    <% if favourite %>
      <%= link_to fa_icon("heart"), post_favourite_path(@post, favourite), method: :delete %>
    <% else %>
      <%= link_to fa_icon("heart-o"), post_favourites_path(@post), method: :post %>
    <% end %>
    <%= @post.favourites.count %>
    <% if can? :manage, @post %>
    <%# if user_signed_in? && current_user == @question.user %>
      <p><%= link_to "Edit", edit_post_path(@post) %></p>
    <% end %>
    <% if can? :manage, @post %>
      <p><%= link_to "Delete", post_path(@post),
                             method: :delete,
                             data: { confirm: "Are you sure?" }  %></p>
    <% end  %>
  </section>
<%# method: :delete asks rails to send a delete request instead of get which is accomplished using javascript and jQuery %>
</article>
<hr>

<div id="create_comment">
  <h4 class = "">Add a comment: </h4>
  <%# render "comments/form" %>
  <%# react_component("CommentForm", {postId: "#{@post.id}"}) %>
</div>

<hr>
<% if @comments  %>
<article class="row">
  <section class="col-md-10 col-md-offset-1">
    <h4>Comments</h4>
      <ul class = "comments-list" id = "comments-loop">
        <%= react_component('Comments', { comments: @comments } ) %>
        <%# @comments.each do |comment| %>
          <%# render "comments/comment", comment: comment %>
          <%# if can? :manage, comment %>
          <%# react_component('Comment', {body: "#{comment.body}", user: "#{comment.user.full_name}", id: "#{comment.id}"}, {prerender: true}) %>
          <%# end %>
        <%# end %>
      </ul>
  </section>
</article>

<article class="row">
  <section class="col-md-10 col-md-offset-5">
    <%= paginate @comments %>
  </section>
</article>
<% end %>