config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  get 'index' => "homes#index"
  get 'about' => "homes#about"

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :comments, only: [:edit, :update]
  resources :favourites, only: [:index]

  resources :users, only: [:new, :create, :show, :edit, :update]

  get "/users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "/users/:id/edit_password" => "users#update_password", as: :update_password

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  get "/search" => "posts#search"
  post "/search" => "posts#search"
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/views/layouts/_flash.html.erb
<% if flash %>
<section class="container">
  <section class="col-md-6 col-md-offset-3 text-lg-center">
  <% flash.each do | message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end  %>
  </section>
</section>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-full navbar-light bg-primary">
  <div class="container">
  <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2"> &#9776; </button>
  <div class="collapse navbar-toggleable-sm" id="exCollapsingNavbar2">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>

        <li class="nav-item active logo">
          <%= link_to "$ tail -f #{current_user.full_name_downcase}/misc.log", root_path, class: "nav-link brand-homepage" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(new_post_path) %> ">
          <%= link_to "add post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(favourites_path) %> ">
          <%= link_to "favourites", favourites_path, class: "nav-link" %>
        </li>
        <li class="nav-item
            <%= 'active' if current_page?(edit_user_path(current_user)) %>">
            <%= link_to "edit profile", edit_user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(sessions_path) %>">
          <%= link_to "log out", sessions_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item <%= 'active' if current_page?(new_user_path) %>">
          <%= link_to "sign up", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(new_session_path) %>">
          <%= link_to "sign in", new_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(new_session_path) %>">
          <%= link_to "sign in with twitter", sign_in_with_twitter_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>b-log</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
</head>
<body>

<header>
  <%= render "layouts/navbar" %>
  <%= render "layouts/flash" %>
</header>
<main class="container">
<%= yield %>
</main>

</body>
</html>
    <%# link_to "All Posts", posts_path  %>
    <%# if user_signed_in? %>
    <!-- Hello <%# link_to current_user.first_name, edit_user_path(current_user) %> -->
          <%# link_to "Sign out", sessions_path, method: :delete %>
          <%# link_to "Create a new Post", new_post_path %>
    <%# else %>
    <%# link_to "Sign Up", new_user_path %>
    <%# link_to "Sign In", new_session_path %>
    <%# end %>
    <!-- <%= link_to "Home", index_path %> -->
    <!-- <%= link_to "About", about_path %> -->
    <!-- <%= link_to "Create Post", new_post_path %> -->
    <!-- <%= link_to "All Posts", posts_path %> -->
    <%# link_to "All Comments", comments_path %>
    <%# link_to "Create Comments", new_comment_path %>